default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: localhost


development:
  <<: *default
  database: piclure_development

test:
  <<: *default
  database: piclure_test

production:
  <<: *default
  database: piclure_production
